name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Replace with your deployment branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install  # Ensure this step is present

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBDEV_LANDING }}'
          projectId: 'webdev-landing'  # Replace with your actual Firebase project ID
